// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           33
// Async Callback (empty):               1
// Total number of exported functions:  36

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    factoring
    (
        init => init
        upgrade => upgrade
        addInvoice => add_invoice
        confirmInvoice => confirm_invoice
        fundInvoice => fund_invoice
        payInvoice => pay_invoice
        payInvoiceAuto => pay_invoice_auto
        fundRemainingAmount => fund_remaining_amount
        calculateReliabilityScore => calculate_reliability_score
        addProcolFunds => add_protocol_funds
        setHatomControllerAddress => set_hatom_controller_address
        removeProcolFunds => remove_protocol_funds
        mintWithUnusedLiquidity => mint_with_unused_liquidity
        exitMarketFarm => exit_market_farm
        withdrawLiquidity => withdraw_liquidity
        claimFarmingRewards => claim_farming_rewards
        addUserToAdminList => add_user_to_admin_list
        removeUserFromAdminList => remove_user_from_admin_list
        addEuriborRate => add_euribor_rate
        addAllowedToken => add_allowed_tokens
        removeAllowedToken => remove_allowed_tokens
        getProtocolFunds => protocol_funds
        getCompany => companies
        getCustomerContract => customer_contracts
        getInvoicesByContract => invoices_by_contract
        getContractsClientByAccount => contracts_client_by_account
        getAvailableAssetByAccountAndIdentifier => assets_by_account_and_identifier
        getFundsByAccount => funds_by_account
        getHatomControllerAddress => hatom_controller_address
        addCompany => add_company
        createFactoringContract => create_factoring_contract
        signContract => sign_contract
        addCompanyAdministrator => add_company_administrator
        addAccountFunds => add_account_funds
        removeAccountFunds => remove_account_funds
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
